// ============================================================
// Program.cs — The Entry Point of the Web API
// ============================================================
// Think of this file as the "front door" of the application.
// When you run the app, .NET starts here. This file:
//   1. Configures what features the app has (services)
//   2. Configures how HTTP requests flow through the app (middleware pipeline)
//   3. Starts the web server and listens for incoming requests
//
// In .NET 6+, the old Startup.cs file was merged into Program.cs.
// Everything is now in one place using the "minimal hosting model".
// ============================================================

// WebApplication.CreateBuilder sets up everything .NET needs to run a web server.
// 'args' are command-line arguments passed when starting the app (e.g., dotnet run --port 8080).
var builder = WebApplication.CreateBuilder(args);

// -------------------------------------------------------
// SECTION 1: Register Services (Dependency Injection)
// -------------------------------------------------------
// "Services" are classes the app needs to function — like a database connection,
// authentication handler, or business logic layer.
//
// Registering them here means you can ask for them anywhere in the app
// without creating them manually. This is called "Dependency Injection" (DI).
//
// Think of it like a toolbox: you declare what tools you need here,
// and .NET hands them to you whenever you ask.
//
// We will add our real services here later (MongoDB, JWT, etc.).
// For now, this section is intentionally empty.

// -------------------------------------------------------
// SECTION 2: Build the App
// -------------------------------------------------------
// builder.Build() finalises all the service registrations above
// and creates the actual web application object.
// After this point, you cannot add new services.
var app = builder.Build();

// -------------------------------------------------------
// SECTION 3: Configure the Middleware Pipeline
// -------------------------------------------------------
// "Middleware" is a chain of steps every HTTP request passes through
// before it reaches your code, and every response passes through on the way back.
//
// Example pipeline for a request to GET /api/products:
//   [Request] → HTTPS redirect → Auth check → Route to controller → [Response]
//
// The ORDER of middleware matters. Each piece runs in the order it's added.

// Automatically redirects http:// requests to https:// for security.
// Example: http://localhost:5047 → https://localhost:7247
app.UseHttpsRedirection();

// -------------------------------------------------------
// SECTION 4: Demo Endpoint (Weather Forecast)
// -------------------------------------------------------
// This is a sample endpoint generated by the dotnet template.
// It demonstrates how to define a minimal API endpoint without a controller.
// We will REPLACE this with our real product/order endpoints later.
//
// app.MapGet maps an HTTP GET request at the given path to a function that handles it.
// The function below returns 5 randomly generated "weather forecasts".

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    // Enumerable.Range(1, 5) creates the sequence [1, 2, 3, 4, 5].
    // .Select() transforms each number into a WeatherForecast record.
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),  // today + N days
            Random.Shared.Next(-20, 55),                         // random temp in Celsius
            summaries[Random.Shared.Next(summaries.Length)]      // random summary word
        ))
        .ToArray(); // convert the lazy sequence to an actual array
    return forecast;
});

// Starts the web server and blocks until the app is shut down (e.g., Ctrl+C).
app.Run();

// -------------------------------------------------------
// WeatherForecast Record (Demo Data Shape)
// -------------------------------------------------------
// A 'record' is a lightweight data class. It is immutable by default
// (you can't change its fields after creation) and has built-in equality
// based on values, not object identity.
//
// This one is just the demo placeholder — we will define our own
// models (Product, Order, Customer) in the Models/ folder.
record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    // A computed property — not stored, just calculated on the fly.
    // The '?' after string means Summary is nullable (it can be null).
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
