// ============================================================
// Customer.cs — The "Customer" Data Model
// ============================================================
// Represents a registered user of the DotShop storefront.
// Stored in the MongoDB "customers" collection.
//
// Note: Authentication data (email + password hash) lives here
// alongside profile data. For a larger system you'd split these
// into separate collections, but for this demo it's fine together.
// ============================================================

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DotShop.Data.Models;

public class Customer
{
    // Unique MongoDB document identifier — auto-generated by MongoDB on insert.
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = null!;

    // The customer's login email. Must be unique across all customers.
    // We enforce this at the service layer before inserting.
    public string Email { get; set; } = null!;

    // NEVER store a plain-text password. We store a BCrypt hash instead.
    //
    // BCrypt is a one-way hashing algorithm designed for passwords:
    //   - You can verify "does this password match this hash?" (BCrypt.Verify)
    //   - But you CANNOT reverse the hash back to the original password
    //   - Even if someone steals the database, they can't read the passwords
    //
    // The "PasswordHash" name makes it obvious to any developer reading this
    // that this field is never the raw password.
    public string PasswordHash { get; set; } = null!;

    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;

    // Role-based access control (RBAC):
    //   "Customer" → can browse, buy, and view their own orders
    //   "Admin"    → can also create/edit products and update order statuses
    //
    // This role is embedded in the JWT token when the customer logs in,
    // so the API can check it on every request without a database lookup.
    public string Role { get; set; } = "Customer";

    // When the account was created — useful for auditing and analytics.
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
